version: 1
default_environment: dev
project_id: 7c6bd0da-da50-4b30-a4ca-c766710728ab
environments:
- name: dev
- name: staging
- name: prod
plugins:
  loaders:
  - name: target-snowflake
    variant: matatika
    pip_url: git+https://github.com/Matatika/target-snowflake@v0.1.1
  transforms:
  - name: dbt-snowflake-monitoring
    variant: matatika
    pip_url: https://github.com/Matatika/dbt-snowflake-monitoring@v4.2.1
  transformers:
  - name: dbt
    variant: dbt-labs
    pip_url: "dbt-core~=1.3.0 dbt-postgres~=1.3.0 dbt-snowflake~=1.3.0\n"
  files:
  - name: analyze-snowflake
    variant: matatika
    pip_url: git+https://github.com/Matatika/analyze-snowflake-monitoring
  - name: files-dbt
    variant: matatika
    pip_url: git+https://github.com/Matatika/files-dbt@v1.0.x.1
  utilities:
  - name: matatika
    variant: matatika
    pip_url: git+https://github.com/Matatika/matatika-ext.git@v0.8.0
jobs:
- name: snowflake-transforms
  tasks:
  - dbt:deps
  - dbt:run
schedules:
- name: Snowflake Transforms
  interval: 0 0 * * * *
  job: snowflake-transforms
