# This file is managed by the 'analyze-snowflake' file bundle and updated automatically when `meltano upgrade` is run.
# To prevent any manual changes from being overwritten, remove the file bundle from `meltano.yml` or disable automatic updates:
#     meltano config --plugin-type=files analyze-snowflake set _update transform/dbt_project.yml false

name: my_meltano_project
version: '1.0'
require-dbt-version: ['>=1.0.0', <2.0.0]
profile: meltano
config-version: 2
model-paths:
- models
analysis-paths:
- analysis
test-paths:
- tests
seed-paths:
- data
macro-paths:
- macros
snapshot-paths:
- snapshots
log-path: logs
packages-install-path: dbt_packages
clean-targets:
- ../.meltano/transformers/dbt/target
- dbt_packages
- logs
models:
  my_meltano_project:
    snowflake_credits:
      # disable the snowflake_credits python dbt model
      # this model runs and checks the resource monitors to get credits left and used.
      # Used with Snowflake credits billing model 
      +enabled: false
  dbt-snowflake-monitoring: {}
vars:
  # disable the dbt-snowflake-monitoring rates from Google Sheet pipeline
  # by default, we expect the daily rates to be available i.e. Snowflake account agreement billing model
  raw_config_rate_sheet_daily_enabled: false
dispatch:
  - macro_namespace: dbt
    search_order:
      - my_meltano_project
      - dbt_snowflake_monitoring
      - dbt
query-comment:
  comment: '{{ dbt_snowflake_monitoring.get_query_comment(node) }}'
  append: true # Snowflake removes prefixed comments.
